server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location /todos {
    proxy_pass http://backend:5000;
  }

  location /metrics {
    proxy_pass http://backend:5000/metrics;
  }
}